version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: odoo_user
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: odoo_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    image: odoo:latest
    container_name: my_odoo
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=my_postgres
      - USER=odoo_user
      - PASSWORD=odoo_password

volumes:
  postgres_data:
